# Habilita o console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Define a URL fixa do banco de dados na memória
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

# Configurações do driver e login padrão
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Show SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true